MDL SDK 2019.1 (317500.1752)

diff --git a/src/mdl/jit/llvm/dist/utils/git-svn/git-svnrevert b/src/mdl/jit/llvm/dist/utils/git-svn/git-svnrevert
--- a/src/mdl/jit/llvm/dist/utils/git-svn/git-svnrevert
+++ b/src/mdl/jit/llvm/dist/utils/git-svn/git-svnrevert
@@ -2,7 +2,7 @@
 
 if [ $# -ne 1 ]; then
     echo "Invalid arguments!"
-    echo "$0 <commit to revert>"
+    echo "$0 <rNNNNNN | git-hash>"
     exit 1
 fi
 
@@ -13,20 +13,32 @@ if [ -n "$(git status -uno -s --porcelain)" ]; then
 fi
 
 COMMIT=$1
-
-SVN_REVISION=$(git svn find-rev "$COMMIT")
-if [ $? -ne 0 ]; then
-    echo "Error! Could not find an svn revision for commit $COMMIT!"
+OTHER=$(git svn find-rev "$COMMIT")
+if [ $? -ne 0 ] || [ "$OTHER" = "" ]; then
+    echo "Error! Could not find an svn/git revision for commit $COMMIT!"
+    echo
+    echo "Possible problems are:"
+    echo "  * Your revision number ($COMMIT) is wrong"
+    echo "  * This tree is not up to date (before that commit)"
+    echo "  * This commit in in another three (llvm, clang, compiler-rt, etc)"
     exit 1
 fi
 
+if [ -n "$(echo $COMMIT | grep '^r[0-9]\+')" ]; then
+  SVN=`echo $COMMIT | sed -e 's/^r//'`
+  GIT=$OTHER
+else
+  SVN=$OTHER
+  GIT=$COMMIT
+fi
+
 # Grab the one line message for our revert commit message.
-ONE_LINE_MSG=$(git log --oneline $COMMIT -1 | cut -f2- -d " ")
+ONE_LINE_MSG=$(git log --oneline $GIT -1 | cut -f2- -d " ")
 
 # Revert the commit.
-git revert --no-commit $COMMIT 2>/dev/null
+git revert --no-commit $GIT 2>/dev/null
 if [ $? -ne 0 ]; then
-    echo "Error! Failed to revert commit $COMMIT. Resetting to head."
+    echo "Error! Failed to revert commit r$SVN. Resetting to head."
     git reset --hard HEAD
     exit 1
 fi
@@ -36,13 +48,13 @@ TEMPLATE="`git rev-parse --git-dir`/git-svn-revert-template"
 cat > $TEMPLATE <<EOF
 Revert "$ONE_LINE_MSG"
 
-This reverts commit r$SVN_REVISION.
+This reverts commit r$SVN.
 EOF
 
 # Begin the commit but give our user an opportunity to edit it.
 git commit --file="$TEMPLATE" --edit
 if [ $? -ne 0 ]; then
-    echo "Error! Failed to commit reverting commit for commit $COMMIT. Reverting to head."
+    echo "Error! Failed to commit reverting commit for commit r$SVN. Reverting to head."
     git reset --hard HEAD
     rm -rf $TEMPLATE
     exit 1
